// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPnesKm0YtnntVg0Yez5EGKv7rWFmXm8k',
    appId: '1:655448867197:web:2ff8e19f847ed8278c0c14',
    messagingSenderId: '655448867197',
    projectId: 'viewtofaizdesk',
    authDomain: 'viewtofaizdesk.firebaseapp.com',
    storageBucket: 'viewtofaizdesk.appspot.com',
    measurementId: 'G-TDLD43G8XZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA14QgPal3M5N8YQsP-AKZrYTIOEscS5UA',
    appId: '1:655448867197:android:3f984a332828754f8c0c14',
    messagingSenderId: '655448867197',
    projectId: 'viewtofaizdesk',
    storageBucket: 'viewtofaizdesk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2NYJ0_6hRMBtPbDjK5boB9IGh9QHL8EU',
    appId: '1:655448867197:ios:aa22bc5018033c328c0c14',
    messagingSenderId: '655448867197',
    projectId: 'viewtofaizdesk',
    storageBucket: 'viewtofaizdesk.appspot.com',
    iosClientId: '655448867197-utmvq9q7nk41tf0jtto34ib6ourg91hd.apps.googleusercontent.com',
    iosBundleId: 'com.mhdfaiz.portfolio.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2NYJ0_6hRMBtPbDjK5boB9IGh9QHL8EU',
    appId: '1:655448867197:ios:aa22bc5018033c328c0c14',
    messagingSenderId: '655448867197',
    projectId: 'viewtofaizdesk',
    storageBucket: 'viewtofaizdesk.appspot.com',
    iosClientId: '655448867197-utmvq9q7nk41tf0jtto34ib6ourg91hd.apps.googleusercontent.com',
    iosBundleId: 'com.mhdfaiz.portfolio.portfolio',
  );
}
